Version 4
SymbolType BLOCK
RECTANGLE Normal 64 80 -64 -64
WINDOW 3 64 16 Left 0
SYMATTR Prefix X
PIN 0 -64 BOTTOM 8
PINATTR PinName BOOT
PINATTR SpiceOrder 1
PIN -64 -48 RIGHT 8
PINATTR PinName COMP
PINATTR SpiceOrder 2
PIN -64 -16 RIGHT 8
PINATTR PinName EN
PINATTR SpiceOrder 3
PIN 0 80 TOP 8
PINATTR PinName GND
PINATTR SpiceOrder 4
PIN 64 -48 LEFT 8
PINATTR PinName SW
PINATTR SpiceOrder 5
PIN -64 16 RIGHT 8
PINATTR PinName RT_CLK
PINATTR SpiceOrder 6
PIN -64 48 RIGHT 8
PINATTR PinName VIN
PINATTR SpiceOrder 7
PIN -64 80 RIGHT 8
PINATTR PinName FB
PINATTR SpiceOrder 8
PIN 48 80 TOP 8
PINATTR PinName ThermalPAD
PINATTR SpiceOrder 9
